"""Initial MVP schema

Revision ID: b54982b59870
Revises: 
Create Date: 2026-01-24 19:16:13.063625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54982b59870'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('entity_type', sa.Enum('SOLE_TRADER', 'PARTNERSHIP', 'LLP', 'LIMITED_COMPANY', 'PLC', 'CHARITY', 'OTHER', name='entitytype'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vat_number')
    )
    op.create_table('vat_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'UNDER_REVIEW', 'READY', 'SUBMITTED', 'LOCKED', name='periodstatus'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trail_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vat_period_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.String(length=2000), nullable=True),
    sa.Column('new_value', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vat_period_id'], ['vat_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chaser_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vat_period_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('requested_items', sa.JSON(), nullable=False),
    sa.Column('upload_token', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'REMINDED', 'PARTIALLY_RECEIVED', 'COMPLETE', 'EXPIRED', name='chaserstatus'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message_body', sa.String(length=5000), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vat_period_id'], ['vat_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_token')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vat_period_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('SALES_INVOICES', 'PURCHASE_INVOICES', 'CREDIT_NOTES', 'DEBIT_NOTES', 'BANK_STATEMENTS', 'RECEIPTS', 'CONTRACTS', 'IMPORT_DOCUMENTS', 'EXPORT_DOCUMENTS', 'VAT_CERTIFICATES', 'OTHER', name='evidencecategory'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETE', 'VALIDATED', 'EXCEPTION', name='evidencestatus'), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=False),
    sa.Column('received_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vat_period_id'], ['vat_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chaser_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chaser_request_id', sa.Integer(), nullable=False),
    sa.Column('responder_email', sa.String(length=255), nullable=True),
    sa.Column('responder_name', sa.String(length=255), nullable=True),
    sa.Column('documents_uploaded', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chaser_request_id'], ['chaser_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_item_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'EXTRACTED', 'VALIDATED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('document_type', sa.Enum('INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', 'RECEIPT', 'BANK_STATEMENT', 'CONTRACT', 'IMPORT_DECLARATION', 'EXPORT_DECLARATION', 'VAT_CERTIFICATE', 'OTHER', name='documenttype'), nullable=True),
    sa.Column('processing_error', sa.String(length=2000), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_vat_number', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_vat_number', sa.String(length=20), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('REQUIRED_FIELDS', 'VAT_NUMBER_FORMAT', 'DATE_IN_PERIOD', 'TOTALS_MATCH', 'VAT_RATE_VALID', 'DUPLICATE_DETECTION', 'AI_ANOMALY', 'CURRENCY_VALID', 'SUPPLIER_VALID', name='ruletype'), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'WARNING', 'SKIPPED', name='validationstatus'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('details', sa.String(length=2000), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('actual_value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('chaser_responses')
    op.drop_table('evidence_items')
    op.drop_table('chaser_requests')
    op.drop_table('audit_trail_entries')
    op.drop_table('vat_periods')
    op.drop_table('clients')
    # ### end Alembic commands ###
